apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hammurapi.fullname" . }}
  labels: {{- include "hammurapi.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
