apiVersion: v1
kind: Service
metadata:
  name: {{ include "hammurapi.fullname" . }}-api
  labels:
    {{- include "hammurapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "hammurapi.selector" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - { name: http, port: 8080, targetPort: http }
    - { name: internal, port: 8081, targetPort: internal }
    - { name: service, port: 9100, targetPort: service }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hammurapi.fullname" . }}-worker
  labels:
    {{- include "hammurapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  selector: {{- include "hammurapi.selector" (dict "root" . "component" "worker") | nindent 4 }}
  ports:
    - { name: service, port: 9100, targetPort: service }
{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hammurapi.fullname" . }}-web
  labels:
    {{- include "hammurapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "hammurapi.selector" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - { name: http, port: 8080, targetPort: http }
{{- end }}
